modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "tat"
version = "${version}"
displayName = "Toil and Trouble"
authors = "Me!"
description = '''
Modern Witchery ofr the Modern Witch!
'''
#logoFile = ""

[[dependencies.tat]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tat]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"